some changes in Makefile for running in my environment
issue:
    /bin/bash: line 1: cd: null directory
    info: Unconfined mode: false
    error: Directory /home/alex/code/primes_plummer_all_languages/my_updates/Primes/tools/-f does not exist!
    (node:898152) [DEP0060] DeprecationWarning: The `util._extend` API is deprecated. Please use Object.assign() instead.
    (Use `node --trace-deprecation ...` to show where the warning was created)

Primes correct_issue_on_my_env ✗ bash --version
GNU bash, version 5.3.9(1)-release (x86_64-pc-linux-gnu)

Primes correct_issue_on_my_env ❯ make --version
GNU Make 4.4.1
Built for x86_64-pc-linux-gnu

Primes correct_issue_on_my_env ❯ hostnamectl
Operating System: Arch Linux
          Kernel: Linux 6.19.6-arch1-1
    Architecture: x86-64